baseURL = "https://papers.freebsd.org/"
languageCode = "en-us"
title = "FreeBSD Presentations and Papers"
publishDir = "public_html"
pluralizeListTitles = false
theme = "hugo-theme-learn"
preserveTaxonomyNames = true

[permalinks]
  post = "/:year/:title/"

[params]
  subtitle = "The collected works of the FreeBSD community as presented at various conferences and summits.  Please send pull request to https://github.com/freebsd/freebsd-papers/ ."
  themeVariant = "red"

[taxonomies]
  author = "author"
